version: '3'
services:
  db:
    image: postgres
    volumes:
      - .:/ruby_practice/db
  web:
    build: .
    command: rails server -p 5000 -b 0.0.0.0
    volumes:
      - .:/ruby_practice
    ports:
      - "5000:5000"
    links:
      - db
      - elasticsearch
    depends_on:
      - db
      - elasticsearch
  elasticsearch:
    image: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      #cd /etc/elasticsearch/ to see settings
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=0.0.0.0
      - cluster.name=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:  
      - /usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana
    links:
      - elasticsearch
    ports:
      - 5601:5601
  