# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3487e9125a3ca82ba1d814894db58d5b8201cc224ff09a943b30063ceb52fcebe848b66e510ba958e21d4aa44544dbe4db0284e43c35ba91881cba6e802facc

test:
  secret_key_base: 41f0daa7774e51306f16023e17d313b723cada71e2e408143eaf70ccd61101c6c00600fbbc0f199df85f5853607eece8269c9619a88da5c7d9592ac1f27002a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
